### ISSUE TITLE
Catch timeout error from WCIVF to avoid page loading entirely

### ISSUE THREAD

**Issue by michaeljcollinsuk** [DemocracyClub/WhoCanIVoteFor#757]
Have found a postcode that sometimes causes a timeout error - this appears to be when WDIV times out trying to get  polling station info https://github.com/DemocracyClub/WhoCanIVoteFor/blob/master/wcivf/apps/elections/views/postcode_view.py#L66

As this postcode has a high number of addresses, sometimes a timeout is returned. This then causes the whole page to fail to load.

Instead, we should catch this timeout exception, and hide the polling station info card. This will mean that we can still display other information cards about the ballots.

**Comment by symroe** [comment]
I think this should be implemented with https://docs.python-requests.org/en/latest/user/quickstart/#timeouts

**Comment by chris48s** [comment]
As well as working around it in WCIVF, if there are requests that are taking long enough to cause a problem for downstream API consumers, that is a performance bug in WDIV that should be fixed.

**Comment by chris48s** [comment]
guess that'll be https://github.com/DemocracyClub/UK-Polling-Stations/pull/3678 then :bulb:

**Comment by symroe** [comment]
Yep!

But also, this issue is still valid, for example we see higher latency sometimes when deploying WDIV. We don't want that site to take down this site, so catching a timeout is still good here.
